### ISSUE TITLE
Uncaught Error: Cannot find module 'acorn/dist/acorn_csp.js'

### ISSUE THREAD

**Issue by GregoryCollett** [speckjs/atom-speckjs#14]
[Enter steps to reproduce below:]
1. Try to install package...
2. Hurray you receive the issue...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [speckjs](https://github.com/speckjs/atom-speckjs) package, v1.0.0
### Stack Trace

Uncaught Error: Cannot find module 'acorn/dist/acorn_csp.js'

```
At module.js:336

Error: Cannot find module 'acorn/dist/acorn_csp.js'
  at Module._resolveFilename (module.js:334:15)
  at Function.exports.register.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/Users/GCollett/.atom/packages/speckjs/node_modules/speckjs/src/parsing/parse-comments.js:26:13)
  at Module._compile (module.js:428:26)
  at Object.keys.forEach.Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/Users/GCollett/.atom/packages/speckjs/node_modules/speckjs/src/speck.js:2:16)
  at Module._compile (module.js:428:26)
  at Object.keys.forEach.Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at /Users/GCollett/.atom/packages/speckjs/lib/speckjs.coffee:2:30
  at exports.allowUnsafeEval (/Users/GCollett/.atom/packages/atom-beautify/node_modules/loophole/lib/loophole.js:14:14)
  at Object.<anonymous> (/Users/GCollett/.atom/packages/speckjs/lib/speckjs.coffee:2:11)
  at Object.<anonymous> (/Users/GCollett/.atom/packages/speckjs/lib/speckjs.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.keys.forEach.Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:725:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:250:14)
  at PackageDetailView.module.exports.PackageDetailView.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:215:26)
  at PackageDetailView.module.exports.PackageDetailView.completeInitialzation (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:158:12)
  at PackageDetailView.module.exports.PackageDetailView.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:170:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:301:17
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:664:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:452:26
  at module.exports.PackageManager.runCommand.exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
  at module.exports.BufferedProcess.handleEvents.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:467:12)

```
### Commands

```
     -1:37.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:28.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
autoclose-html, v0.19.0
docblockr, v0.7.3
editorconfig, v1.2.1
emmet, v2.3.13
minimap, v4.16.0
react, v0.12.10
terminal-plus, v0.13.0
trailing-spaces, v0.3.2
whitespace, v0.32.0

# Dev
No dev packages
```

**Comment by GregoryCollett** [comment]
closing as never addressed
